"""Formfeed API client (spec 10 §1): sync and async, retries on 429/503, idempotency keys, typed errors."""

from .client import AsyncFormfeed, Formfeed
from .errors import FormfeedError
from .models import (
    Brand,
    Channel,
    ChannelList,
    Diagnostic,
    Job,
    LibraryFile,
    LibraryFilePage,
    ListenSession,
    PdfInfo,
    Render,
    RenderInput,
    RenderPage,
    SharedPartial,
    SharedPartialPutResult,
    Template,
    TemplateFile,
    Usage,
    TemplateValidation,
    TemplateVersion,
    SchemaChange,
    SchemaCheck,
    WebhookEndpoint,
    WebhookEvent,
    WebhookResend,
)
from .webhooks import parse_webhook_event, verify_webhook_signature

__all__ = [
    "AsyncFormfeed",
    "Formfeed",
    "FormfeedError",
    "Brand",
    "Channel",
    "ChannelList",
    "Diagnostic",
    "Job",
    "LibraryFile",
    "LibraryFilePage",
    "ListenSession",
    "PdfInfo",
    "Render",
    "RenderInput",
    "RenderPage",
    "SharedPartial",
    "SharedPartialPutResult",
    "Template",
    "TemplateFile",
    "TemplateValidation",
    "Usage",
    "TemplateVersion",
    "SchemaChange",
    "SchemaCheck",
    "WebhookEndpoint",
    "WebhookEvent",
    "WebhookResend",
    "parse_webhook_event",
    "verify_webhook_signature",
]

__version__ = "0.3.8"
