// Bundles the scripts that run inside the editor's preview frames (plan 16, decision 7) into
// `src/lib/generated/frames.ts` as string constants. `--check` fails when the committed file is stale;
// `frames.spec.ts` runs the same comparison with the engine's tests.
//
//   node packages/engine/scripts/build-frames.mjs [--check]
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export const outputPath = join(root, 'src/lib/generated/frames.ts');

/** Constant name → entry, in the order they appear in the generated module. */
const entries = {
  textEditRuntime: 'src/frame/text-edit.entry.ts',
  fitRuntime: 'src/frame/fit.entry.ts',
  stageRuntime: 'src/frame/stage.entry.ts',
  auditRuntime: 'src/frame/audit.entry.ts',
};

async function bundle(entry) {
  const result = await build({
    entryPoints: [join(root, entry)],
    bundle: true,
    write: false,
    format: 'iife',
    target: 'es2020',
    minify: true,
    legalComments: 'none',
    logLevel: 'silent',
  });
  return result.outputFiles[0].text.trim();
}

/** The generated module's text. */
export async function framesModule() {
  const lines = [
    '// Generated by `nx run engine:frames` (scripts/build-frames.mjs) from src/frame/*.entry.ts. Do not edit.',
    '/* eslint-disable */',
  ];
  for (const [name, entry] of Object.entries(entries)) {
    lines.push(
      '',
      `/** Bundled from ${entry}. */`,
      `export const ${name} = ${JSON.stringify(await bundle(entry))};`,
    );
  }
  return `${lines.join('\n')}\n`;
}

// run directly (drive letters may differ in case on Windows), not imported by the spec
if (
  process.argv[1] &&
  resolve(process.argv[1]).toLowerCase() ===
    fileURLToPath(import.meta.url).toLowerCase()
) {
  const next = await framesModule();
  let current = '';
  try {
    // a checkout with CRLF line endings is still current
    current = readFileSync(outputPath, 'utf8').replace(/\r\n/g, '\n');
  } catch {
    // not generated yet
  }
  if (process.argv.includes('--check')) {
    if (current !== next) {
      console.error(
        'src/lib/generated/frames.ts is stale: run `pnpm nx run engine:frames` and commit the result.',
      );
      process.exit(1);
    }
    console.log('frames.ts is current');
  } else if (current !== next) {
    writeFileSync(outputPath, next);
    console.log('wrote src/lib/generated/frames.ts');
  } else console.log('frames.ts is current');
}
