import { originNote, type NamedObject, type TemplateTypes, type TypeNode } from './model';

const KEYWORDS = new Set([
  'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del',
  'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal',
  'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield',
]);

const isIdentifier = (key: string) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) && !KEYWORDS.has(key);

/** `delivery-note` → `delivery_note`; a keyword or a leading digit gets an underscore. */
function methodName(slug: string): string {
  const name = slug.replace(/[^A-Za-z0-9_]+/g, '_').toLowerCase();
  return isIdentifier(name) ? name : `${/^[0-9]/.test(name) ? 't_' : ''}${name}${KEYWORDS.has(name) ? '_' : ''}`;
}

/** `quoteRefs`: the functional TypedDict form evaluates its values at once, so names become strings. */
function expression(node: TypeNode, quoteRefs: boolean): string {
  switch (node.kind) {
    case 'unknown':
      return 'Any';
    case 'never':
      return 'Never';
    case 'primitive':
      return { string: 'str', number: 'float', integer: 'int', boolean: 'bool', null: 'None' }[node.name];
    case 'literal':
      return node.value === null ? 'None' : `Literal[${pythonLiteral(node.value)}]`;
    case 'array':
      return `list[${expression(node.items, quoteRefs)}]`;
    case 'record':
      return `dict[str, ${expression(node.values, quoteRefs)}]`;
    case 'ref':
      return quoteRefs ? JSON.stringify(node.name) : node.name;
    case 'union': {
      // literals fold into one Literal[...], which reads better and is what type checkers print
      const literals = node.members.filter(
        (m): m is Extract<TypeNode, { kind: 'literal' }> => m.kind === 'literal' && m.value !== null,
      );
      const rest = node.members.filter((m) => !(m.kind === 'literal' && m.value !== null));
      const parts = [
        ...(literals.length ? [`Literal[${literals.map((l) => pythonLiteral(l.value)).join(', ')}]`] : []),
        ...rest.map((m) => expression(m, quoteRefs)),
      ];
      // `"Name" | None` is not valid at runtime; quoted references need Optional/Union spelling
      if (quoteRefs && rest.some((m) => m.kind === 'ref')) return `Union[${parts.join(', ')}]`;
      return parts.join(' | ');
    }
    case 'intersection':
      // Python's typing has no intersection; the first part is the closest honest type
      return expression(node.members[0] ?? { kind: 'unknown' }, quoteRefs);
  }
}

function pythonLiteral(value: string | number | boolean | null): string {
  if (value === null) return 'None';
  if (typeof value === 'boolean') return value ? 'True' : 'False';
  return JSON.stringify(value);
}

function docstring(lines: string[], indent: string): string[] {
  if (lines.length === 0) return [];
  const safe = lines.map((line) => line.replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"'));
  if (safe.length === 1) return [`${indent}"""${safe[0]}"""`];
  return [`${indent}"""${safe[0]}`, ...safe.slice(1).map((line) => `${indent}${line}`.trimEnd()), `${indent}"""`];
}

function emitObject(object: NamedObject): string[] {
  const functional = object.fields.some((f) => !isIdentifier(f.key));
  const field = (type: TypeNode, required: boolean, quote: boolean) => {
    const text = expression(type, quote);
    return required ? text : `NotRequired[${text}]`;
  };
  if (functional) {
    const out = [`${object.name} = TypedDict(`, `    ${JSON.stringify(object.name)},`, '    {'];
    for (const f of object.fields) out.push(`        ${JSON.stringify(f.key)}: ${field(f.type, f.required, true)},`);
    out.push('    },', ')');
    if (object.doc.length) out.unshift(...object.doc.map((line) => `# ${line}`));
    return out;
  }
  const out = [`class ${object.name}(TypedDict):`, ...docstring(object.doc, '    ')];
  for (const f of object.fields) {
    out.push(`    ${f.key}: ${field(f.type, f.required, false)}`);
    out.push(...docstring(f.doc, '    '));
  }
  if (object.fields.length === 0) out.push('    pass');
  return out;
}

/**
 * `formfeed_templates.py`: a TypedDict per template and `typed(client)`, whose `renders.create`
 * overloads check `data` for the known slugs and fall back to the plain signature otherwise.
 */
export function emitPython(templates: TemplateTypes[]): string {
  const lines: string[] = [
    '# Generated by `formfeed types`. Do not edit: run it again when a template schema changes.',
    '#',
    ...templates.map((t) => `# ${t.slug}: ${originNote(t)}`),
    '',
    'from __future__ import annotations',
    '',
    'from typing import Any, Literal, Union, cast',
    '',
    'from typing_extensions import Never, NotRequired, TypedDict',
    '',
    'from formfeed import AsyncFormfeed, Formfeed, Render',
    '',
    '__all__ = [',
    ...templates.map((t) => `    ${JSON.stringify(t.rootName)},`),
    '    "TypedRenders",',
    '    "AsyncTypedRenders",',
    '    "typed",',
    '    "typed_async",',
    ']',
  ];
  for (const template of templates) {
    lines.push('', '', `# --- ${template.slug}`);
    // children before parents: the functional form and runtime `get_type_hints` both need that order
    for (const object of [...template.objects].reverse()) lines.push('', ...emitObject(object));
    const isClass = template.root.kind === 'ref' && template.root.name === template.rootName;
    if (!isClass) lines.push('', `${template.rootName} = ${expression(template.root, true)}`);
  }

  // A method per template rather than overloads of `create`: an overload keyed by the slug falls
  // through to the untyped signature when the data is wrong, so a type checker would never complain.
  const wrapper = (name: string, isAsync: boolean) => {
    const example = templates[0] ? methodName(templates[0].slug) : 'invoice';
    const out = [
      '',
      '',
      `class ${name}:`,
      `    """Renders with \`data\` checked per template: \`${isAsync ? 'await typed_async(client)' : 'typed(client)'}.${example}(data, **options)\`."""`,
      '',
      `    def __init__(self, client: ${isAsync ? 'AsyncFormfeed' : 'Formfeed'}) -> None:`,
      '        self._renders: Any = client.renders',
    ];
    for (const t of templates) {
      out.push(
        '',
        `    ${isAsync ? 'async ' : ''}def ${methodName(t.slug)}(self, data: ${t.rootName}, **options: Any) -> Render:`,
        `        return cast(Render, ${isAsync ? 'await ' : ''}self._renders.create(template=${JSON.stringify(t.slug)}, data=data, **options))`,
      );
    }
    return out;
  };
  lines.push(...wrapper('TypedRenders', false), ...wrapper('AsyncTypedRenders', true));
  lines.push(
    '',
    '',
    'def typed(client: Formfeed) -> TypedRenders:',
    '    return TypedRenders(client)',
    '',
    '',
    'def typed_async(client: AsyncFormfeed) -> AsyncTypedRenders:',
    '    return AsyncTypedRenders(client)',
  );
  return lines.join('\n') + '\n';
}
