import { originNote, type NamedObject, type TemplateTypes, type TypeNode } from './model';

export interface TypeScriptOptions {
  /** The module the generated file augments; `@formfeed/sdk` for customers. */
  sdkModule?: string;
}

const identifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const quoteKey = (key: string) => (identifier.test(key) ? key : JSON.stringify(key));

function expression(node: TypeNode, nested = false): string {
  switch (node.kind) {
    case 'unknown':
      return 'unknown';
    case 'never':
      return 'never';
    case 'primitive':
      return node.name === 'integer' ? 'number' : node.name;
    case 'literal':
      return JSON.stringify(node.value);
    case 'array': {
      const inner = expression(node.items, true);
      return /[|&]/.test(inner) ? `Array<${expression(node.items)}>` : `${inner}[]`;
    }
    case 'record':
      return `Record<string, ${expression(node.values)}>`;
    case 'ref':
      return node.name;
    case 'union': {
      const text = node.members.map((m) => expression(m, true)).join(' | ');
      return nested ? `(${text})` : text;
    }
    case 'intersection': {
      const text = node.members.map((m) => expression(m, true)).join(' & ');
      return nested ? `(${text})` : text;
    }
  }
}

function docBlock(lines: string[], indent: string): string[] {
  if (lines.length === 0) return [];
  const safe = lines.map((line) => line.replace(/\*\//g, '*\\/'));
  if (safe.length === 1) return [`${indent}/** ${safe[0]} */`];
  return [`${indent}/**`, ...safe.map((line) => `${indent} * ${line}`.trimEnd()), `${indent} */`];
}

function emitObject(object: NamedObject): string[] {
  const out = [...docBlock(object.doc, ''), `export interface ${object.name} {`];
  for (const field of object.fields) {
    out.push(...docBlock(field.doc, '  '));
    out.push(`  ${quoteKey(field.key)}${field.required ? '' : '?'}: ${expression(field.type)};`);
  }
  if (object.extra) {
    // an index signature must admit every listed field too, so the extra type only documents itself
    out.push(`  /** Further fields: ${expression(object.extra).replace(/\*\//g, '*\\/')} */`);
    out.push('  [key: string]: unknown;');
  }
  out.push('}');
  return out;
}

/**
 * `formfeed.d.ts`: one data type per template plus the augmentation of `FormfeedTemplates`, which
 * makes `renders.create({ template: 'invoice', data })` check `data` against `InvoiceData`.
 */
export function emitTypeScript(templates: TemplateTypes[], options: TypeScriptOptions = {}): string {
  const sdk = options.sdkModule ?? '@formfeed/sdk';
  const lines: string[] = [
    '// Generated by `formfeed types`. Do not edit: run it again when a template schema changes.',
    '//',
    ...templates.map((t) => `// ${t.slug}: ${originNote(t)}`),
    '',
    `declare module ${JSON.stringify(sdk)} {`,
    '  interface FormfeedTemplates {',
    ...templates.map((t) => `    ${JSON.stringify(t.slug)}: ${t.rootName};`),
    '  }',
    '}',
  ];
  for (const template of templates) {
    lines.push('', `// --- ${template.slug}`);
    const isInterface = template.root.kind === 'ref' && template.root.name === template.rootName;
    if (!isInterface) lines.push('', `export type ${template.rootName} = ${expression(template.root)};`);
    for (const object of template.objects) lines.push('', ...emitObject(object));
  }
  if (templates.length === 0) lines.push('', 'export {};');
  return lines.join('\n') + '\n';
}
